### ISSUE TITLE
Creating an app

### ISSUE THREAD

**Issue by sawantsaini** [notmaintained/shopify_api#13] opened 2014-07-30 11:22 UTC
hi sandeep
..i am trying to make an app in shopify.i am not familar with shopify app.i have installed composer.json file and downloaded vendor folder on local host......please guide me what to do next.I am following these link.
1.)http://www.geek-alpha.com/php/using-php-connect-shopify-api-installation-dependencies-database/  (completed)
2.http://www.geek-alpha.com/php/using-php-connect-shopify-api-make-api-calls/ (i ahve an doubt in this link .where to put this code.?shall i put this code on local host files?

**Comment by sawantsaini** [comment] 2014-07-30 11:45
In this link 
http://wern-ancheta.com/blog/2013/11/09/getting-started-with-shopify-app-development/ 

How to do ........Getting App Permissions on local  host.?
where i shall save this file (shopify_app.php) 
(Is this  file should be in local host if yes  ,then In which folder  of local host,i would put the files what is way of calling those files.
Plz also tell the name of those files...
Thanx in Advance.

**Comment by sandeepshetty** [comment] 2014-11-22 03:56
[Latest version](https://github.com/phpish/shopify) has an [example app](https://github.com/phpish/shopify-skeleton) that might help.

Closing, since this looks like a support issue and not a bug report.

**Closed as completed by sandeepshetty** 2014-11-22 03:56 UTC
