### ISSUE TITLE
Cannot get the access token

### ISSUE THREAD

**Issue by richajain** [notmaintained/shopify_api#12] opened 2014-05-21 07:34 UTC
I am unable to get the access token. I have passed 'shop' in my URL but cannot understand want do I need to pass in 'code'. I guess its due to 'code' being an empty parameter I am unable to generate the access token.

**Comment by sandeepshetty** [comment] 2014-11-22 03:54
Closing, since this looks like a support issue and not a bug report.

**Closed as completed by sandeepshetty** 2014-11-22 03:54 UTC
